# OpenML files not used:
# gina-agnostic  - file not available on OpenML
# amazon-commerce-reviews -- currently slow and needs to be sped up.

real_files = [
	'credit-g',
	'blood-transfusion-service-center',
	'monks-problems-2',
	'tic-tac-toe',
	'qsar-biodeg',
	'wdbc',
	'phoneme',
	'diabetes',
	'ozone-level-8hr',
	'hill-valley',
	'kc2',
	'eeg-eye-state',
	'climate-model-simulation-crashes',
	'spambase',
	'ilpd',
	'one-hundred-plants-margin',
	'banknote-authentication',
	'mozilla4',
	'electricity',
	'madelon',
	'scene',
	'musk',
	'nomao',
	'bank-marketing',
	'MagicTelescope',
	'Click_prediction_small',
	'PhishingWebsites',
	'nursery',
	'page-blocks',
	'hypothyroid',
	'yeast',
	'kropt',
	'CreditCardSubset',
	'shuttle',
	'Satellite',
	'baseball',
	'mc1',
	'pc1',
	'cardiotocography',
	'kr-vs-k',
	'volcanoes-a1',
	'wine-quality-white',
	'car-evaluation',
	'solar-flare',
	'allbp',
	'allrep',
	'dis',
	'car',
	'steel-plates-fault'
	]